# site name
prefixName: 佳境
siteName: Shmily
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.gif
url: Shmilyqjj.github.io
description: 记得每天要早睡呀！
cdn: https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources
pjax: 1
# 1开启
mathjax: 0

notice: 佳境的个人博客正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/, fa: fa-th-list faa-bounce },
    看剧: {path: /bangumi/, fa: fa-film faa-vertical },
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改 1-8王者荣耀  9-26灵笼
bg:
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(9).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(10).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(11).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(12).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(13).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(14).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(15).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(16).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(17).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(18).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(19).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(20).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(21).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(22).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(23).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(24).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(25).webp
  - https://cdn.jsdelivr.net/gh/Shmilyqjj/Shmily-Web@master/cdn_sources/img/cover/(26).webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 佳境的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}


# your site build time or founded date
siteBuildingTime: 09/21/2019

#social  url, img PC端配置
social:
  github: {url: https://github.com/Shmilyqjj, img: /img/social/github.png}
  CloudMusic: {url: http://music.163.com/artist?id=13610347&userid=318926152, img: /img/social/wangyiyun.png}
  bilibili: {url: https://space.bilibili.com/55921513, img: /img/social/bilibili.png}
  email: {url: mailto:710552907@qq.com?subject=test&cc=sample@hotmail.com&body=use mailto sample, img: /img/social/email.svg}
  qq: {url: http://wpa.qq.com/msgrd?v=3&uin=710552907&site=qq&menu=yes, img: /img/social/qq.png}
  wechat: {url: /#, qrcode: /img/custom/WeChat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/Shmilyqjj, fa: fa-github, color: 333}
  weibo: {url: http://music.163.com/artist?id=13610347&userid=318926152, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=710552907&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}
  # wechat: {url: https://wpa.qq.com/msgrd?v=3&uin=710552907&site=qq&menu=yes, fa: fa-weichat, color: 25c6fe}

donate:
  alipay: /img/custom/donate/aliPayQR.jpg
  wechat: /img/custom/donate/weChatQR.png
  wechatSQ: /img/custom/donate/weChatSQ.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: http://pyp1a3dme.bkt.clouddn.com/
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: blog-my_heart_will_go_on.mp4,blog-big_fish.mp4,blog_sakura.mp4,videoblog-metro.mp4,videoblog-xxdsx.mp4


aplayer: 
  id: 2368663800
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true


# Valine (+LeanCloud)
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
# 在Leancloud -> 设置 -> 安全中心 -> Web 安全域名 把你的域名加进去
valine: true
v_appId: zUyVEaHo59RUUwiPTChPEeBj-gzGzoHsz
v_appKey: xIEyTcrkTuJLz6ewPbpTj8mz
notify: false  # mail notifier , https://github.com/xCss/Valine/wiki
verify: false  # Verification code
guest_info: nick,mail,link # custom comment header
pageSize: 30


#sitemap-搜索引擎爬取（待完善）
baidu_push: true
